version: '3'
name: user-management-gateway-stack
services:

  postgres:
    container_name: user_management_postgres
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespw
      DB_USERNAME: username
      DB_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - user_management_postgres_data:/var/lib/postgresql/data
    networks:
      - user_management_gateway_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  user_management_gateway_network:
    driver: bridge

volumes:
  user_management_postgres_data:
